In [1]:
import numpy as np

In [4]:
np1 = np.linspace(1,10,7)        # Linearly spaced

In [5]:
np1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((4,4))*2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [15]:
np.diag([3,6,9])

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

In [16]:
np.diag([3,6,9,12])**3

array([[  27,    0,    0,    0],
       [   0,  216,    0,    0],
       [   0,    0,  729,    0],
       [   0,    0,    0, 1728]], dtype=int32)

In [18]:
np.diag([3,6,9,12,19])//3

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 6]], dtype=int32)

In [19]:
np1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [22]:
id(np1)

1804204478992

In [20]:
np2 = np1

In [21]:
np2

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [23]:
id(np2)

1804204478992

In [24]:
np.shares_memory(np1,np2)

True

In [25]:
np3 = np2.copy()

In [27]:
id(np2),id(np3)

(1804204478992, 1804220942576)

In [28]:
np.shares_memory(np2,np3)

False

In [30]:
fours = np.ones((5,5))*4

In [31]:
fours

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [33]:
fours[2,4] = 54

In [34]:
fours

array([[ 4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4., 54.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [37]:
fours[2,4]            # Only returns the specific element

54.0

In [36]:
fours[[2,4]]          # Returns the 2nd and 4th row of a matrix

array([[ 4.,  4.,  4.,  4., 54.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [41]:
diag_mat = np.diag([1,2,3,4,5,6])

In [42]:
diag_mat[[2,5]]

array([[0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 6]])

In [45]:
np.random.rand(1,5)

array([[0.70432882, 0.84273022, 0.5843222 , 0.50043995, 0.83010235]])

In [46]:
np.random.randn(1,5)

array([[ 0.05441636, -0.52433725,  1.02751441,  1.95911784, -0.16111099]])

In [9]:
A = np.array([[1,2,3],[4,5,6],[1,1,1]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [4]:
A.shape

(3, 3)

In [5]:
A.ndim

2

In [6]:
type(A)

numpy.ndarray

In [8]:
A.diagonal()

array([1, 5, 1])

In [45]:
B = np.array([[1,2,3],[4,5,6],[1,1,1]])

In [11]:
id(A)

2560363732304

In [12]:
id(B)

2560363819056

In [13]:
C = A

In [14]:
id(A)

2560363732304

In [15]:
id(C)

2560363732304

In [16]:
A == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
A == C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
C == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
C = C * 2

In [20]:
C == B

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [31]:
isinstance(C,np.int)

False

In [35]:
np.asarray(((4,5,6),(6,7,8)))

array([[4, 5, 6],
       [6, 7, 8]])

In [36]:
np.array_equal(C, B)

False

In [38]:
np.logical_or(A,B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [46]:
np.logical_and(A,B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
B = B * 0

In [42]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [43]:
B

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
np.logical_or(A,B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
np.logical_and(A,B)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [52]:
np.sin(np.arange(6))

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [53]:
np.log(5)

1.6094379124341003

In [54]:
np.exp(np.arange(1,10,2))

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03])

In [56]:
np.square(np.arange(1,10,2))

array([ 1,  9, 25, 49, 81], dtype=int32)

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [62]:
flat_A = A.flatten()

In [63]:
flat_A

array([1, 2, 3, 4, 5, 6, 1, 1, 1])

In [64]:
flat_A.ndim

1

In [65]:
flat_A.shape

(9,)

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [71]:
A.ravel()

array([1, 2, 3, 4, 5, 6, 1, 1, 1])

In [88]:
A[2:4] = [2,3,4]

In [97]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [100]:
A = np.append(A,[[6,7,8]],axis=0)

In [101]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [6, 7, 8]])

In [103]:
A = np.insert(A,2,[[0,9,8]],axis=0)
A

array([[1, 2, 3],
       [4, 5, 6],
       [0, 9, 8],
       [2, 3, 4],
       [6, 7, 8]])

In [111]:
%%timeit
np.insert(A,3,[[1,1,1,1,1]],axis=1)

62.7 µs ± 4.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [112]:
A

array([[1, 2, 3, 1, 1],
       [4, 5, 6, 1, 1],
       [0, 9, 8, 1, 1],
       [2, 3, 4, 1, 1],
       [6, 7, 8, 1, 1]])

In [113]:
A = np.insert(A,3,[[1,1,1,1,1]],axis=1)
A

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 1, 1, 1],
       [0, 9, 8, 1, 1, 1],
       [2, 3, 4, 1, 1, 1],
       [6, 7, 8, 1, 1, 1]])

In [114]:
A

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 1, 1, 1],
       [0, 9, 8, 1, 1, 1],
       [2, 3, 4, 1, 1, 1],
       [6, 7, 8, 1, 1, 1]])

In [115]:
A.sum()

83

In [116]:
A.sum(axis=0)

array([13, 26, 29,  5,  5,  5])

In [117]:
A.sum(axis=1)

array([ 9, 18, 20, 12, 24])

In [118]:
A.min()

0

In [119]:
A.min(axis=1)

array([1, 1, 0, 1, 1])

In [120]:
A.min(axis=0)

array([0, 2, 3, 1, 1, 1])

In [121]:
A.argmin()

12

In [122]:
A.argmax()

13

In [126]:
np.all([True, True, False])

False

In [127]:
np.any([True, False , False])

True

In [128]:
np.all([1,1,1,1,1, 0])

False

In [130]:
np.any([1,1,1,1,1])

True

In [132]:
np.any([1,1,1,1,0])

True

In [136]:
np.any([0,1,0,0,0,0])

True

In [137]:
A

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 1, 1, 1],
       [0, 9, 8, 1, 1, 1],
       [2, 3, 4, 1, 1, 1],
       [6, 7, 8, 1, 1, 1]])

In [138]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [142]:
B = np.append(B, [[5,6,7],[7,8,9],[9,9,9]], axis=0)

In [150]:
B = np.delete(A,[3,4,5],axis=1)

In [151]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [0, 9, 8],
       [2, 3, 4],
       [6, 7, 8]])

In [153]:
A = np.delete(A,[3,4,5],axis=1)

In [154]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [0, 9, 8],
       [2, 3, 4],
       [6, 7, 8]])

In [155]:
A * B

array([[ 1,  4,  9],
       [16, 25, 36],
       [ 0, 81, 64],
       [ 4,  9, 16],
       [36, 49, 64]])

In [157]:
B = B.reshape(3,5)
A.dot(B)

array([[ 22,  14,  39,  41,  33],
       [ 52,  32,  93,  98,  78],
       [ 78,  32, 129, 128,  82],
       [ 32,  20,  57,  60,  48],
       [ 72,  44, 129, 136, 108]])

##### **NUMPY Broadcasting**

In [158]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [0, 9, 8],
       [2, 3, 4],
       [6, 7, 8]])

In [183]:
B

array([[1, 2, 3, 4, 5],
       [6, 0, 9, 8, 2],
       [3, 4, 6, 7, 8]])

In [185]:
A.T

array([[1, 4, 0, 2, 6],
       [2, 5, 9, 3, 7],
       [3, 6, 8, 4, 8]])

In [184]:
B.T

array([[1, 6, 3],
       [2, 0, 4],
       [3, 9, 6],
       [4, 8, 7],
       [5, 2, 8]])

In [186]:
np.transpose([A[:,1]])

array([[2],
       [5],
       [9],
       [3],
       [7]])

In [189]:
D = np.tile(np.transpose([A[:,1]]),(1,3))

In [190]:
D

array([[2, 2, 2],
       [5, 5, 5],
       [9, 9, 9],
       [3, 3, 3],
       [7, 7, 7]])

In [191]:
D + A

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 9, 18, 17],
       [ 5,  6,  7],
       [13, 14, 15]])