In [1]:
import numpy as np

In [4]:
np1 = np.linspace(1,10,7)        # Linearly spaced

In [5]:
np1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((4,4))*2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [15]:
np.diag([3,6,9])

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

In [16]:
np.diag([3,6,9,12])**3

array([[  27,    0,    0,    0],
       [   0,  216,    0,    0],
       [   0,    0,  729,    0],
       [   0,    0,    0, 1728]], dtype=int32)

In [18]:
np.diag([3,6,9,12,19])//3

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 6]], dtype=int32)

In [19]:
np1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [22]:
id(np1)

1804204478992

In [20]:
np2 = np1

In [21]:
np2

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [23]:
id(np2)

1804204478992

In [24]:
np.shares_memory(np1,np2)

True

In [25]:
np3 = np2.copy()

In [27]:
id(np2),id(np3)

(1804204478992, 1804220942576)

In [28]:
np.shares_memory(np2,np3)

False

In [30]:
fours = np.ones((5,5))*4

In [31]:
fours

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [33]:
fours[2,4] = 54

In [34]:
fours

array([[ 4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4., 54.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [37]:
fours[2,4]            # Only returns the specific element

54.0

In [36]:
fours[[2,4]]          # Returns the 2nd and 4th row of a matrix

array([[ 4.,  4.,  4.,  4., 54.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [41]:
diag_mat = np.diag([1,2,3,4,5,6])

In [42]:
diag_mat[[2,5]]

array([[0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 6]])

In [45]:
np.random.rand(1,5)

array([[0.70432882, 0.84273022, 0.5843222 , 0.50043995, 0.83010235]])

In [46]:
np.random.randn(1,5)

array([[ 0.05441636, -0.52433725,  1.02751441,  1.95911784, -0.16111099]])