# ***`Feature Encoding`***

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy 
import category_encoders as ce

from scipy.io.arff import loadarff
from sklearn.datasets import load_breast_cancer, load_diabetes

%matplotlib inline

pd.set_option('display.max_columns',50)

In [2]:
def apply_decode(df_name):
    """
    Description: Function created for changing the character encoding
    Input: It accepts one parameter:
    df_name : `Pandas DataFrame`
    Return: `utf-8` encoded DataFrame
    """
    for col in df_name.columns:
        if df_name[col].dtype != 'float64':
            df_name[col] = df_name[col].apply(lambda val : val.decode('utf-8'))
    return df_name

In [3]:
path = os.getcwd()
file = path+'\\Autism-Child-Data.arff'

autism_dataset = pd.DataFrame(loadarff(file)[0])
autism_dataset.head()

A1_Score A2_Score A3_Score A4_Score A5_Score A6_Score A7_Score A8_Score  \
0     b'1'     b'1'     b'0'     b'0'     b'1'     b'1'     b'0'     b'1'   
1     b'1'     b'1'     b'0'     b'0'     b'1'     b'1'     b'0'     b'1'   
2     b'1'     b'1'     b'0'     b'0'     b'0'     b'1'     b'1'     b'1'   
3     b'0'     b'1'     b'0'     b'0'     b'1'     b'1'     b'0'     b'0'   
4     b'1'     b'1'     b'1'     b'1'     b'1'     b'1'     b'1'     b'1'   

  A9_Score A10_Score  age gender           ethnicity jundice austim  \
0     b'0'      b'0'  6.0   b'm'           b'Others'   b'no'  b'no'   
1     b'0'      b'0'  6.0   b'm'  b'Middle Eastern '   b'no'  b'no'   
2     b'0'      b'0'  6.0   b'm'                b'?'   b'no'  b'no'   
3     b'0'      b'1'  5.0   b'f'                b'?'  b'yes'  b'no'   
4     b'1'      b'1'  5.0   b'm'           b'Others'  b'yes'  b'no'   

      contry_of_res used_app_before  result       age_desc   relation  \
0         b'Jordan'           b'no'     5.0  b'4-11 years'  b'Parent'   
1         b'Jordan'           b'no'     5.0  b'4-11 years'  b'Parent'   
2         b'Jordan'          b'yes'     5.0  b'4-11 years'       b'?'   
3         b'Jordan'           b'no'     4.0  b'4-11 years'       b'?'   
4  b'United States'           b'no'    10.0  b'4-11 years'  b'Parent'   

  Class/ASD  
0     b'NO'  
1     b'NO'  
2     b'NO'  
3     b'NO'  
4    b'YES'

In [4]:
autism_df = apply_decode(autism_dataset)
autism_df = autism_df.applymap(lambda val: None if val == '?' else val)
autism_df.head()

A1_Score A2_Score A3_Score A4_Score A5_Score A6_Score A7_Score A8_Score  \
0        1        1        0        0        1        1        0        1   
1        1        1        0        0        1        1        0        1   
2        1        1        0        0        0        1        1        1   
3        0        1        0        0        1        1        0        0   
4        1        1        1        1        1        1        1        1   

  A9_Score A10_Score  age gender        ethnicity jundice austim  \
0        0         0  6.0      m           Others      no     no   
1        0         0  6.0      m  Middle Eastern       no     no   
2        0         0  6.0      m             None      no     no   
3        0         1  5.0      f             None     yes     no   
4        1         1  5.0      m           Others     yes     no   

   contry_of_res used_app_before  result    age_desc relation Class/ASD  
0         Jordan              no     5.0  4-11 years   Parent        NO  
1         Jordan              no     5.0  4-11 years   Parent        NO  
2         Jordan             yes     5.0  4-11 years     None        NO  
3         Jordan              no     4.0  4-11 years     None        NO  
4  United States              no    10.0  4-11 years   Parent       YES

In [5]:
autism_df.head()

A1_Score A2_Score A3_Score A4_Score A5_Score A6_Score A7_Score A8_Score  \
0        1        1        0        0        1        1        0        1   
1        1        1        0        0        1        1        0        1   
2        1        1        0        0        0        1        1        1   
3        0        1        0        0        1        1        0        0   
4        1        1        1        1        1        1        1        1   

  A9_Score A10_Score  age gender        ethnicity jundice austim  \
0        0         0  6.0      m           Others      no     no   
1        0         0  6.0      m  Middle Eastern       no     no   
2        0         0  6.0      m             None      no     no   
3        0         1  5.0      f             None     yes     no   
4        1         1  5.0      m           Others     yes     no   

   contry_of_res used_app_before  result    age_desc relation Class/ASD  
0         Jordan              no     5.0  4-11 years   Parent        NO  
1         Jordan              no     5.0  4-11 years   Parent        NO  
2         Jordan             yes     5.0  4-11 years     None        NO  
3         Jordan              no     4.0  4-11 years     None        NO  
4  United States              no    10.0  4-11 years   Parent       YES

In [6]:
autism_df.dtypes

A1_Score            object
A2_Score            object
A3_Score            object
A4_Score            object
A5_Score            object
A6_Score            object
A7_Score            object
A8_Score            object
A9_Score            object
A10_Score           object
age                float64
gender              object
ethnicity           object
jundice             object
austim              object
contry_of_res       object
used_app_before     object
result             float64
age_desc            object
relation            object
Class/ASD           object
dtype: object

In [7]:
autism_df.isna().sum()

A1_Score            0
A2_Score            0
A3_Score            0
A4_Score            0
A5_Score            0
A6_Score            0
A7_Score            0
A8_Score            0
A9_Score            0
A10_Score           0
age                 4
gender              0
ethnicity          43
jundice             0
austim              0
contry_of_res       0
used_app_before     0
result              0
age_desc            0
relation           43
Class/ASD           0
dtype: int64

In [8]:
autism_df.columns

Index(['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender',
       'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before',
       'result', 'age_desc', 'relation', 'Class/ASD'],
      dtype='object')

In [9]:
for col in ['A1_Score','A2_Score','A3_Score','A4_Score','A5_Score','A6_Score','A7_Score','A8_Score','A9_Score','A10_Score']:
    autism_df[col] = autism_df[col].astype(int)

In [10]:
autism_df.dtypes

A1_Score             int32
A2_Score             int32
A3_Score             int32
A4_Score             int32
A5_Score             int32
A6_Score             int32
A7_Score             int32
A8_Score             int32
A9_Score             int32
A10_Score            int32
age                float64
gender              object
ethnicity           object
jundice             object
austim              object
contry_of_res       object
used_app_before     object
result             float64
age_desc            object
relation            object
Class/ASD           object
dtype: object

In [11]:
autism_df.fillna(method='backfill',inplace=True)

In [12]:
autism_df.isna().sum()

A1_Score           0
A2_Score           0
A3_Score           0
A4_Score           0
A5_Score           0
A6_Score           0
A7_Score           0
A8_Score           0
A9_Score           0
A10_Score          0
age                0
gender             0
ethnicity          0
jundice            0
austim             0
contry_of_res      0
used_app_before    0
result             0
age_desc           0
relation           0
Class/ASD          0
dtype: int64

In [13]:
autism_df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         0         0         1         1         0   
1         1         1         0         0         1         1         0   
2         1         1         0         0         0         1         1   
3         0         1         0         0         1         1         0   
4         1         1         1         1         1         1         1   

   A8_Score  A9_Score  A10_Score  age gender        ethnicity jundice austim  \
0         1         0          0  6.0      m           Others      no     no   
1         1         0          0  6.0      m  Middle Eastern       no     no   
2         1         0          0  6.0      m           Others      no     no   
3         0         0          1  5.0      f           Others     yes     no   
4         1         1          1  5.0      m           Others     yes     no   

   contry_of_res used_app_before  result    age_desc relation Class/ASD  
0         Jordan              no     5.0  4-11 years   Parent        NO  
1         Jordan              no     5.0  4-11 years   Parent        NO  
2         Jordan             yes     5.0  4-11 years   Parent        NO  
3         Jordan              no     4.0  4-11 years   Parent        NO  
4  United States              no    10.0  4-11 years   Parent       YES

In [14]:
X = autism_df[['age','gender','ethnicity','jundice','austim','contry_of_res','used_app_before','result','age_desc','relation']].copy(deep=True)
y = autism_df['Class/ASD'].copy(deep=True)

In [15]:
X.head()

age gender        ethnicity jundice austim  contry_of_res used_app_before  \
0  6.0      m           Others      no     no         Jordan              no   
1  6.0      m  Middle Eastern       no     no         Jordan              no   
2  6.0      m           Others      no     no         Jordan             yes   
3  5.0      f           Others     yes     no         Jordan              no   
4  5.0      m           Others     yes     no  United States              no   

   result    age_desc relation  
0     5.0  4-11 years   Parent  
1     5.0  4-11 years   Parent  
2     5.0  4-11 years   Parent  
3     4.0  4-11 years   Parent  
4    10.0  4-11 years   Parent

In [16]:
y.head()

0     NO
1     NO
2     NO
3     NO
4    YES
Name: Class/ASD, dtype: object

## **Ordinal_Encoding**

### **CASE-I**
#### **Using all the values of RELATION variable**

In [17]:
X['relation'] = X['relation'].apply(lambda val: str(val).capitalize())

In [18]:
X['relation'].value_counts()

Parent                      251
Relative                     18
Health care professional     15
Self                          8
Name: relation, dtype: int64

In [19]:
oe = ce.OrdinalEncoder(verbose=1,
                       mapping=[{'col':'relation','mapping':{'Self':1,'Parent':2,'Relative':3,'Health care professional':4}}])

In [20]:
oe.fit(X=X)

OrdinalEncoder(cols=['gender', 'ethnicity', 'jundice', 'austim',
                     'contry_of_res', 'used_app_before', 'age_desc',
                     'relation'],
               mapping=[{'col': 'relation',
                         'mapping': {'Health care professional': 4, 'Parent': 2,
                                     'Relative': 3, 'Self': 1}}],
               verbose=1)

In [21]:
X['oe_relation'] = oe.transform(X)['relation']

In [22]:
X.head()

age gender        ethnicity jundice austim  contry_of_res used_app_before  \
0  6.0      m           Others      no     no         Jordan              no   
1  6.0      m  Middle Eastern       no     no         Jordan              no   
2  6.0      m           Others      no     no         Jordan             yes   
3  5.0      f           Others     yes     no         Jordan              no   
4  5.0      m           Others     yes     no  United States              no   

   result    age_desc relation  oe_relation  
0     5.0  4-11 years   Parent            2  
1     5.0  4-11 years   Parent            2  
2     5.0  4-11 years   Parent            2  
3     4.0  4-11 years   Parent            2  
4    10.0  4-11 years   Parent            2

In [24]:
X['oe_relation'].value_counts()

2    251
3     18
4     15
1      8
Name: oe_relation, dtype: int64

### **CASE-II**
#### **Manually Ordinal encoding the classes with one class labelled as -1**

In [25]:
relation_dict = {'Self':1,'Parent':2,'Relative':3,'Health care professional':-1}
relation_dict

{'Self': 1, 'Parent': 2, 'Relative': 3, 'Health care professional': -1}

In [26]:
X['relation'].apply(lambda val: relation_dict[val]).value_counts()

 2    251
 3     18
-1     15
 1      8
Name: relation, dtype: int64

## **Count_Encoding**

### **CASE-I**
#### **Using all the values of RELATION variable**

In [27]:
cnt_end = ce.CountEncoder(cols='relation')

In [28]:
cnt_end.fit(X=X)

CountEncoder(cols=['relation'], combine_min_nan_groups=True)

In [29]:
cnt_end.transform(X)['relation'].value_counts()

251    251
18      18
15      15
8        8
Name: relation, dtype: int64

### **CASE-II**
#### **Manually Count encoding the classes**

In [30]:
relation_cnt_dict = X['relation'].value_counts().to_dict()
X['relation'].apply(lambda val: relation_cnt_dict.get(val)).value_counts()

251    251
18      18
15      15
8        8
Name: relation, dtype: int64

## **One-Hot_Encoding**

### **CASE-I**
#### **Using all the values of RELATION variable**

In [31]:
ohe = ce.OneHotEncoder(cols='relation')

In [32]:
ohe.fit(X=X)

c:\users\rajsh\appdata\local\programs\python\python36\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


OneHotEncoder(cols=['relation'])

In [33]:
ohe.transform(X)

age gender        ethnicity jundice austim   contry_of_res  \
0    6.0      m           Others      no     no          Jordan   
1    6.0      m  Middle Eastern       no     no          Jordan   
2    6.0      m           Others      no     no          Jordan   
3    5.0      f           Others     yes     no          Jordan   
4    5.0      m           Others     yes     no   United States   
..   ...    ...              ...     ...    ...             ...   
287  7.0      f   White-European     yes    yes  United Kingdom   
288  7.0      f   White-European     yes    yes       Australia   
289  4.0      m           Latino      no     no          Brazil   
290  4.0      m      South Asian      no     no           India   
291  4.0      f      South Asian      no     no           India   

    used_app_before  result    age_desc  relation_1  relation_2  relation_3  \
0                no     5.0  4-11 years           1           0           0   
1                no     5.0  4-11 years           1           0           0   
2               yes     5.0  4-11 years           1           0           0   
3                no     4.0  4-11 years           1           0           0   
4                no    10.0  4-11 years           1           0           0   
..              ...     ...         ...         ...         ...         ...   
287              no    10.0  4-11 years           1           0           0   
288              no     4.0  4-11 years           1           0           0   
289              no     7.0  4-11 years           1           0           0   
290              no     9.0  4-11 years           1           0           0   
291              no     3.0  4-11 years           1           0           0   

     relation_4  oe_relation  
0             0            2  
1             0            2  
2             0            2  
3             0            2  
4             0            2  
..          ...          ...  
287           0            2  
288           0            2  
289           0            2  
290           0            2  
291           0            2  

[292 rows x 14 columns]

### **CASE-II**
#### **Manually one-hot encoding the classes**

##### **Step-1 : Ordinal Encoded variable**

In [34]:
X['oe_relation'].values

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 1, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 3, 2, 1, 2, 2,
       2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 4,
       2, 2, 2, 2, 3, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 3,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4,
       2, 2, 2, 2, 2, 2])

##### **Step-2 : Creating the Identity Matrix based on the unique categories**

In [35]:
eye = np.eye(len(set(X['oe_relation']))).astype(int)
eye

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

##### **Step-3 : Accessing the rows of above created Identity Matrix based on the value in Ordinal Encoded Feature(e.g. 1,2,3 and 4)**

In [36]:
eye[1-1], eye[2-1], eye[3-1], eye[4-1]

(array([1, 0, 0, 0]),
 array([0, 1, 0, 0]),
 array([0, 0, 1, 0]),
 array([0, 0, 0, 1]))

##### **Step-4 : Converting the row into Series**

In [37]:
pd.Series(eye[1-1])

0    1
1    0
2    0
3    0
dtype: int32

#### **Now, applying the above steps on the dataframe column**

In [38]:
X['oe_relation'].apply(lambda val: pd.Series(np.diag(np.ones(len(set(X['oe_relation']))))[val-1].astype(int))).head(25)

0  1  2  3
0   0  1  0  0
1   0  1  0  0
2   0  1  0  0
3   0  1  0  0
4   0  1  0  0
5   0  1  0  0
6   0  1  0  0
7   0  1  0  0
8   0  1  0  0
9   1  0  0  0
10  1  0  0  0
11  0  1  0  0
12  0  1  0  0
13  0  1  0  0
14  0  1  0  0
15  0  1  0  0
16  0  1  0  0
17  0  1  0  0
18  0  1  0  0
19  0  1  0  0
20  0  1  0  0
21  0  1  0  0
22  0  1  0  0
23  0  1  0  0
24  0  0  1  0

https://www.kaggle.com/subinium/11-categorical-encoders-and-benchmark

https://towardsdatascience.com/beyond-one-hot-17-ways-of-transforming-categorical-features-into-numeric-features-57f54f199ea4

In [83]:
se1 = ce.SumEncoder(cols='relation')

In [84]:
se1.fit(X)

c:\users\rajsh\appdata\local\programs\python\python36\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


SumEncoder(cols=['relation'],
           mapping=[{'col': 'relation',
                     'mapping':     relation_0  relation_1  relation_2
 1         1.0         0.0         0.0
 2         0.0         1.0         0.0
 3         0.0         0.0         1.0
 4        -1.0        -1.0        -1.0
-1         0.0         0.0         0.0
-2         0.0         0.0         0.0}])

In [88]:
se1.transform(X,y).tail(50)

intercept   age gender        ethnicity jundice austim  \
242          1   6.0      m  Middle Eastern      yes     no   
243          1   9.0      f  Middle Eastern      yes     no   
244          1   7.0      m  Middle Eastern      yes     no   
245          1   5.0      m  Middle Eastern       no     no   
246          1   5.0      m  Middle Eastern      yes     no   
247          1  10.0      m  Middle Eastern       no    yes   
248          1   7.0      m  Middle Eastern       no     no   
249          1   9.0      m  Middle Eastern      yes     no   
250          1   7.0      m  Middle Eastern      yes     no   
251          1   7.0      m  Middle Eastern      yes     no   
252          1   7.0      m  Middle Eastern      yes     no   
253          1   9.0      f  Middle Eastern       no     no   
254          1   5.0      m  Middle Eastern      yes     no   
255          1   4.0      m      South Asian      no     no   
256          1   5.0      m            Asian      no    yes   
257          1   4.0      f      South Asian      no     no   
258          1   5.0      m      South Asian      no     no   
259          1   5.0      m            Black      no     no   
260          1   4.0      m   White-European      no     no   
261          1   6.0      m            Asian      no     no   
262          1   6.0      f            Black      no     no   
263          1   5.0      m            Asian      no     no   
264          1  11.0      m   White-European      no     no   
265          1  10.0      m            Black     yes     no   
266          1   4.0      m      South Asian      no     no   
267          1   5.0      m           Others      no     no   
268          1  10.0      m  Middle Eastern      yes     no   
269          1   9.0      m  Middle Eastern      yes     no   
270          1   4.0      m            Asian      no     no   
271          1   4.0      f   White-European      no    yes   
272          1   5.0      m            Black      no     no   
273          1   8.0      m   White-European      no    yes   
274          1   8.0      m   White-European     yes     no   
275          1   6.0      m            Asian      no     no   
276          1  11.0      m            Asian      no     no   
277          1  10.0      f            Asian      no     no   
278          1   6.0      f   White-European      no     no   
279          1   6.0      m            Asian      no    yes   
280          1   4.0      m            Black      no    yes   
281          1   4.0      m   White-European      no     no   
282          1   4.0      f   White-European     yes     no   
283          1   5.0      m           Others      no     no   
284          1  10.0      f   White-European      no     no   
285          1  10.0      f   White-European      no     no   
286          1   5.0      f           Latino     yes     no   
287          1   7.0      f   White-European     yes    yes   
288          1   7.0      f   White-European     yes    yes   
289          1   4.0      m           Latino      no     no   
290          1   4.0      m      South Asian      no     no   
291          1   4.0      f      South Asian      no     no   

            contry_of_res used_app_before  result    age_desc  relation_0  \
242          Saudi Arabia              no     3.0  4-11 years         1.0   
243          Saudi Arabia              no     3.0  4-11 years         1.0   
244                Jordan              no     6.0  4-11 years         1.0   
245                Jordan              no     6.0  4-11 years         1.0   
246  United Arab Emirates              no     4.0  4-11 years         1.0   
247  United Arab Emirates              no     1.0  4-11 years         1.0   
248                Jordan              no     3.0  4-11 years         1.0   
249                 Egypt              no     6.0  4-11 years         1.0   
250                 Egypt              no     7.0  4-11 years         1.0   
251                 E

In [46]:
from sklearn.datasets import load_boston

In [47]:
boston = load_boston()

In [48]:
XX = pd.DataFrame(boston.data,columns=boston.feature_names)
yy = boston.target

In [60]:
XX.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [82]:
XX['CHAS'].value_counts()

0.0    471
1.0     35
Name: CHAS, dtype: int64

In [74]:
xxx = pd.DataFrame(np.c_[np.array(XX),yy])
feats = list(boston.feature_names)
feats.extend(['Label'])

In [76]:
xxx.columns = feats

In [77]:
xxx.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Label  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [78]:
se = ce.SumEncoder(cols='CHAS')

In [79]:
se.fit(X=XX,y=yy)

c:\users\rajsh\appdata\local\programs\python\python36\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


SumEncoder(cols=['CHAS'],
           mapping=[{'col': 'CHAS',
                     'mapping':     CHAS_0
 1     1.0
 2    -1.0
-1     0.0
-2     0.0}])

In [80]:
se.transform(XX).head(30)

intercept     CRIM    ZN  INDUS  CHAS_0    NOX     RM    AGE     DIS  RAD  \
0           1  0.00632  18.0   2.31     1.0  0.538  6.575   65.2  4.0900  1.0   
1           1  0.02731   0.0   7.07     1.0  0.469  6.421   78.9  4.9671  2.0   
2           1  0.02729   0.0   7.07     1.0  0.469  7.185   61.1  4.9671  2.0   
3           1  0.03237   0.0   2.18     1.0  0.458  6.998   45.8  6.0622  3.0   
4           1  0.06905   0.0   2.18     1.0  0.458  7.147   54.2  6.0622  3.0   
5           1  0.02985   0.0   2.18     1.0  0.458  6.430   58.7  6.0622  3.0   
6           1  0.08829  12.5   7.87     1.0  0.524  6.012   66.6  5.5605  5.0   
7           1  0.14455  12.5   7.87     1.0  0.524  6.172   96.1  5.9505  5.0   
8           1  0.21124  12.5   7.87     1.0  0.524  5.631  100.0  6.0821  5.0   
9           1  0.17004  12.5   7.87     1.0  0.524  6.004   85.9  6.5921  5.0   
10          1  0.22489  12.5   7.87     1.0  0.524  6.377   94.3  6.3467  5.0   
11          1  0.11747  12.5   7.87     1.0  0.524  6.009   82.9  6.2267  5.0   
12          1  0.09378  12.5   7.87     1.0  0.524  5.889   39.0  5.4509  5.0   
13          1  0.62976   0.0   8.14     1.0  0.538  5.949   61.8  4.7075  4.0   
14          1  0.63796   0.0   8.14     1.0  0.538  6.096   84.5  4.4619  4.0   
15          1  0.62739   0.0   8.14     1.0  0.538  5.834   56.5  4.4986  4.0   
16          1  1.05393   0.0   8.14     1.0  0.538  5.935   29.3  4.4986  4.0   
17          1  0.78420   0.0   8.14     1.0  0.538  5.990   81.7  4.2579  4.0   
18          1  0.80271   0.0   8.14     1.0  0.538  5.456   36.6  3.7965  4.0   
19          1  0.72580   0.0   8.14     1.0  0.538  5.727   69.5  3.7965  4.0   
20          1  1.25179   0.0   8.14     1.0  0.538  5.570   98.1  3.7979  4.0   
21          1  0.85204   0.0   8.14     1.0  0.538  5.965   89.2  4.0123  4.0   
22          1  1.23247   0.0   8.14     1.0  0.538  6.142   91.7  3.9769  4.0   
23          1  0.98843   0.0   8.14     1.0  0.538  5.813  100.0  4.0952  4.0   
24          1  0.75026   0.0   8.14     1.0  0.538  5.924   94.1  4.3996  4.0   
25          1  0.84054   0.0   8.14     1.0  0.538  5.599   85.7  4.4546  4.0   
26          1  0.67191   0.0   8.14     1.0  0.538  5.813   90.3  4.6820  4.0   
27          1  0.95577   0.0   8.14     1.0  0.538  6.047   88.8  4.4534  4.0   
28          1  0.77299   0.0   8.14     1.0  0.538  6.495   94.4  4.4547  4.0   
29          1  1.00245   0.0   8.14     1.0  0.538  6.674   87.3  4.2390  4.0   

      TAX  PTRATIO       B  LSTAT  
0   296.0     15.3  396.90   4.98  
1   242.0     17.8  396.90   9.14  
2   242.0     17.8  392.83   4.03  
3   222.0     18.7  394.63   2.94  
4   222.0     18.7  396.90   5.33  
5   222.0     18.7  394.12   5.21  
6   311.0     15.2  395.60  12.43  
7   311.0     15.2  396.90  19.15  
8   311.0     15.2  386.63  29.93  
9   311.0     15.2  386.71  17.10  
10  311.0     15.2  392.52  20.45  
11  311.0     15.2  396.90  13.27  
12  311.0     15.2  390.50  15.71  
13  307.0     21.0  396.90   8.26  
14  307.0     21.0  380.02  10.26  
15  307.0     21.0  395.62   8.47  
16  307.0     21.0  386.85   6.58  
17  307.0     21.0  386.75  14.67  
18  307.0     21.0  288.99  11.69  
19  307.0     21.0  390.95  11.28  
20  307.0     21.0  376.57  21.02  
21  307.0     21.0  392.53  13.83  
22  307.0     21.0  396.90  18.72  
23  307.0     21.0  394.54  19.88  
24  307.0     21.0  394.33  16.30  
25  307.0     21.0  303.42  16.51  
26  307.0     21.0  376.88  14.81  
27  307.0     21.0  306.38  17.28  
28  307.0     21.0  387.94  12.80  
29  307.0     21.0  380.23  11.98